openapi: 3.0.0
info:
  title: Starship API
  description: Routes for bulding starships
  version: 0.1.9
paths:
  /starships:
    get:
      summary: Returns a list of starships.
      responses:
        '200':
          description: A JSON array of starships names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Starship'

    post:
      summary: Creates a single starship
      requestBody:
        description: The name of model to create a starship
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                model:
                  type: string
      responses:
        '200':
          description: Successfully created starship

  /starships/{starshipId}:
    get:
      summary: Returns a single starship.
      parameters:
        - in: path
          name: starshipId
          schema:
            type: string
          required: true
          description: ID of the starship
      responses:
        '200':
          description: a single starship
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Starship'

    delete:
      summary: Deletes a single starship
      parameters:
        - in: path
          name: starshipId
          schema:
            type: string
          required: true
          description: ID of the starship
      responses:
        '200':
          description: Successfully deleted starship if found

components:
  schemas:
    Starship:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        model:
          type: string
        components:
          type: object
